grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
      max_depth: 3
      min_samples_split: 3
    search_param_grid:
      min_samples_leaf:
      - 6
      max_depth:
      - 4
      - 5
      min_samples_split:
      - 4
      - 5

